"""
Applet: NJ Departures
Summary: Nearby NJ departures
Description: Watch up to six nearby stops at once - NJ Transit buses, light rail
             and NY Waterway ferries - and see the next departure from each.
             Bus times are realtime (GPS-based); light rail and ferry come from
             published timetables.
Author: Joshua J Brewster
"""

load("cache.star", "cache")
load("encoding/json.star", "json")
load("hash.star", "hash")
load("http.star", "http")
load("math.star", "math")
load("render.star", "render")
load("schema.star", "schema")
load("secret.star", "secret")
load("time.star", "time")

# ---------------------------------------------------------------------------
# Static data, generated by pipeline/build_index.py
# ---------------------------------------------------------------------------
#
# A Tidbyt app is a single sandboxed file with no filesystem, so the stop index
# lives in this app's repo and is fetched over HTTP. Stops are bucketed into
# 0.1-degree grid cells so that finding "stops near me" costs one small
# download instead of an index of 16.5k bus stops.
#
# Repoint this at your own fork if you regenerate the data.
DATA_BASE = "https://raw.githubusercontent.com/joshbrewster42/tidbyt-nj-transit/main/data/v1"

CELL_SIZE = 0.1  # must match CELL_SIZE in pipeline/build_index.py

# Static data changes only when NJ Transit publishes a new booking, so cache it
# hard. Realtime predictions obviously cannot be.
# Both agencies publish Eastern times, so all arithmetic happens here rather
# than wherever the device happens to be.
AGENCY_TZ = "America/New_York"

TTL_STATIC = 86400
TTL_REALTIME = 30

# A countdown goes wrong quietly. If the device loses connectivity it keeps
# showing whatever it last received, so a "3 min" can sit on screen long after
# that bus has gone -- worse than showing nothing, because it is still
# believable. max_age tells the device to stop displaying this render once it
# is this old.
MAX_AGE = 120

# ---------------------------------------------------------------------------
# NJ Transit realtime bus API
# ---------------------------------------------------------------------------
#
# Registration: https://developer.njtransit.com/registration/
#
# Auth is a username/password exchange, not a bare API key: POST credentials to
# authenticateUser, get back a UserToken good for roughly 24 hours, then pass
# that token to the data endpoints. We cache the token so a device refreshing
# every 15 seconds is not re-authenticating constantly.
BUS_API = "https://pcsdata.njtransit.com/api/BUSDV2"
TOKEN_CACHE_KEY = "njt_bus_token_v1"
TOKEN_TTL = 20 * 60 * 60  # refresh well before the ~24h expiry

# Fallback credentials, encrypted with `pixlet encrypt`. These are safe to
# commit because only the holder of the matching private key can reverse them,
# and that is Tidbyt's cloud; secret.decrypt() returns None everywhere else,
# including local development and any self-hosted server.
#
#   pixlet encrypt nj-departures '<your njtransit username>'
#   pixlet encrypt nj-departures '<your njtransit password>'
#
# They are a fallback rather than the main path. Baking one account into the
# app points every install in the world at the same NJ Transit account and its
# rate limit, and it cannot work off Tidbyt's servers at all, so njt_user and
# njt_pass in the config take priority. See njt_credentials().
NJT_USERNAME_ENC = "AV6+xWcESOn74adQJmtl09df+IAStv+tpiMzHwwAIwx94IuHMJEN0UxyTQe6vZiHKBgRZaKYDMMBKxumB+hvjz5gG6CqlkQqEFyz+NHWE+bFtouRun0ddbVPZj1w5cu19IA41qCMFXLDyXZlzEFaY4cllY0="
NJT_PASSWORD_ENC = "AV6+xWcEfFCBU16YmTHaKCz4FCMhs3TzRKkU9qo0iaeh+HKVkgfOwc/UvS/5wqn08YM2slnMjVcn/dcq6WUbQ4qMsKVmwzNbAlq9MUFN+85JdCfUC6sUNxjSdKrOZUubl/eUlTjMqx+2ADLIjpITBHvNudCX"

# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------
# Six numbered slots. A Tidbyt schema is a static form with no "add another",
# so the number of things that can be watched has to be fixed up front.
SLOTS = 6

# With no header, four 7px lines fit on a 32px display. More than four watched
# stops pages between screens.
LINES_PER_PAGE = 4

# A page holds for this long before the next one. At DELAY_MS per frame that is
# PAGE_HOLD_MS / DELAY_MS copies of the same widget, because render.Animation
# treats every child as exactly one frame.
DELAY_MS = 100
PAGE_HOLD_MS = 4000

# A live badge spends most of its cycle showing the route and briefly says
# LIVE instead. At DELAY_MS per frame that is roughly 2.5s then 0.8s.
LIVE_FLASH_ON = 8
LIVE_FLASH_OFF = 25

# Fetch more than fits, so filtering by destination still has something to
# choose from. Only the soonest is shown, but the filter needs candidates.
FETCH_LIMIT = 15

# How many trips to read before sorting. Higher than FETCH_LIMIT because the
# feed is grouped by route, so the soonest departure can be well down the list.
SCAN_LIMIT = 60

# Official NJ Transit route colors, from routes.txt in the GTFS feed.
LINE_COLORS = {
    "HBLR": "#008080",
    "NLR": "#009ad1",
    "RVLN": "#1a1aff",  # feed says 00008B, lifted for legibility on a dark LED
}
BUS_COLOR = "#e8a33d"

# NY Waterway's hull blue. NJ Transit runs no ferries -- the Hudson crossings
# are NY Waterway's, and their feed is a separate source.
FERRY_COLOR = "#1e9bd7"

COLOR_DIM = "#6a6a6a"
COLOR_TEXT = "#ffffff"
COLOR_SOON = "#ff5656"
COLOR_OK = "#4ade80"

# Hue carries urgency, brightness carries confidence. A dimmed countdown is a
# timetable time; a bright one is a vehicle actually being tracked. Keeping
# them on separate channels means a scheduled departure three minutes out can
# still go red.
COLOR_SOON_SCHEDULED = "#99302f"
COLOR_OK_SCHEDULED = "#2b7a4b"

FONT = "tom-thumb"

# Leading badges for the stop picker. Every entry gets one, including buses:
# tagging only the exceptions means the common case carries no marker at all,
# and a list where most rows look identical is a list nobody can scan.
MODE_TAGS = {"b": "BUS", "l": "RAIL", "f": "FERRY"}

# The badge needs a visible separator. Padding it out with spaces does not
# work -- the picker renders as HTML, which collapses runs of whitespace, so
# "BUS  Park Ave" arrives as "BUS Park Ave" and reads as one phrase. The
# middle dot also stays clear of the " - " already used before the route list.
MODE_SEPARATOR = " \u00b7 "

# A floor, not a quota: at least this many light rail stations and ferry
# terminals always make the picker, however far down a distance ranking they
# fall, because bus stops are dense enough to bury a whole mode. Anything
# genuinely close still appears on its own merit. Keeping this at one avoids
# dragging in a second terminal across the river just to fill a slot.
MODE_GUARANTEE = 1

DEFAULT_STOP = json.encode({
    "c": "20783",
    "n": "Hoboken Ave at Summit Ave",
    "m": "b",
    "r": ["119"],
})

# ---------------------------------------------------------------------------
# Geography
# ---------------------------------------------------------------------------

def cell_key(lat, lon):
    """Grid cell containing a point. Mirrors cell_key() in build_index.py."""
    return "%d_%d" % (math.floor(lat / CELL_SIZE), math.floor(lon / CELL_SIZE))

def haversine_km(lat1, lon1, lat2, lon2):
    """Great-circle distance. Good enough for ranking stops a few km apart."""
    r = 6371.0
    p1 = math.radians(lat1)
    p2 = math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) * math.sin(dp / 2) + \
        math.cos(p1) * math.cos(p2) * math.sin(dl / 2) * math.sin(dl / 2)
    return 2 * r * math.atan2(math.sqrt(a), math.sqrt(1 - a))

def fetch_cell(key):
    """Stops in one grid cell, or [] if the cell has none (most of them)."""
    resp = http.get("%s/cells/%s.json" % (DATA_BASE, key), ttl_seconds = TTL_STATIC)
    if resp.status_code != 200:
        return []
    return resp.json()

def nearby_stops(lat, lon, mode = "", limit = 24):
    """Stops near a point, nearest first.

    Fetches the cell containing the point plus the three cells adjacent to
    whichever corner the point sits closest to. That covers the neighbourhood
    without paying for a full 3x3 block, and a cell is ~11km tall so a point
    near an edge still sees across it.
    """
    ci = math.floor(lat / CELL_SIZE)
    cj = math.floor(lon / CELL_SIZE)

    # Which way does the point lean inside its own cell?
    di = 1 if (lat / CELL_SIZE - ci) >= 0.5 else -1
    dj = 1 if (lon / CELL_SIZE - cj) >= 0.5 else -1

    candidates = []
    for (i, j) in [(ci, cj), (ci + di, cj), (ci, cj + dj), (ci + di, cj + dj)]:
        candidates.extend(fetch_cell("%d_%d" % (i, j)))

    scored = []
    for s in candidates:
        # Filter before ranking, or asking for ferries would return the 24
        # nearest stops of any kind and then keep whichever happened to float.
        if mode and s["m"] != mode:
            continue
        scored.append((haversine_km(lat, lon, s["lat"], s["lon"]), s))
    scored = sorted(scored, key = lambda pair: pair[0])

    if mode:
        # One mode is already its own group; nothing can be crowded out.
        return scored[:limit]
    return guarantee_modes(scored, limit)

def guarantee_modes(scored, limit):
    """Nearest stops, but never with a whole mode crowded out.

    Bus stops are dense: from a spot a few blocks inland of Weehawken there are
    two dozen within 0.4 miles, which is enough to push the ferry terminal half
    a mile away off a distance-ranked list entirely. Somebody who wants the
    ferry then cannot find it at all.

    So take the nearest stops as usual, then make sure the closest few light
    rail stations and ferry terminals are in there regardless of where they
    placed, and re-sort so the list still reads by distance.
    """
    chosen = scored[:limit]

    seen = {}
    for (_d, s) in chosen:
        seen[s["m"] + s["c"]] = True

    for mode in ["l", "f"]:
        present = 0
        for (_d, s) in chosen:
            if s["m"] == mode:
                present += 1

        for (dist, s) in scored:
            if present >= MODE_GUARANTEE:
                break
            if s["m"] != mode or seen.get(s["m"] + s["c"]):
                continue
            chosen.append((dist, s))
            seen[s["m"] + s["c"]] = True
            present += 1

    return sorted(chosen, key = lambda pair: pair[0])

# ---------------------------------------------------------------------------
# Realtime bus departures
# ---------------------------------------------------------------------------

def njt_credentials(config):
    """The NJ Transit developer login to authenticate with, or (None, None).

    Config is tried first so the app is not tied to one backend. Only the
    operator holding the matching private key can reverse the ciphertext
    below, and that operator is Tidbyt's cloud; on a self-hosted server
    secret.decrypt() returns None no matter how sound the ciphertext is.
    Registration is free, so a user there supplies their own account instead
    of borrowing the one baked into the source.
    """
    username = config.str("njt_user", "").strip()
    password = config.str("njt_pass", "").strip()
    if username and password:
        return username, password

    # Nothing configured, so fall back to the built-in credentials. These
    # resolve on Tidbyt's servers and nowhere else -- including local dev.
    return secret.decrypt(NJT_USERNAME_ENC), secret.decrypt(NJT_PASSWORD_ENC)

def token_cache_key(username):
    """A cache key scoped to one account.

    The cache is shared by every install of this app, so the single fixed key
    this used to have would serve one user's token to another now that the
    account can differ per user. The username is hashed to keep it out of the
    key, not because the key is published anywhere.
    """
    return "%s_%s" % (TOKEN_CACHE_KEY, hash.sha256(username)[:16])

def forget_bus_token(config):
    """Drop the cached token so the next render authenticates again."""
    username, _ = njt_credentials(config)
    if username:
        cache.set(token_cache_key(username), "", ttl_seconds = 1)

def bus_token(config):
    """A UserToken for the bus API, cached across renders.

    Returns (token, error). Having no credentials and having wrong ones are
    reported separately: both end up with no token, but one is solved by
    filling in the config and the other by correcting it, and a row that says
    the same thing either way sends you looking in the wrong place.
    """
    username, password = njt_credentials(config)
    if not username or not password:
        return None, "add login"

    cache_key = token_cache_key(username)
    cached = cache.get(cache_key)
    if cached:
        return cached, None

    resp = http.post(
        "%s/authenticateUser" % BUS_API,
        form_body = {"username": username, "password": password},
        form_encoding = "application/x-www-form-urlencoded",
    )
    if resp.status_code != 200:
        return None, "api error"

    body = resp.json()
    token = body.get("UserToken")
    if not token or body.get("Authenticated") not in ("True", True, "true"):
        # The endpoint answers 200 with Authenticated false for a rejected
        # login, so this is the only place a bad username or password shows up.
        return None, "bad login"

    cache.set(cache_key, token, ttl_seconds = TOKEN_TTL)
    return token, None

def bus_departures(stop_code, now, config):
    """Next buses from a stop, as a list of display rows.

    Returns (departures, error). The API returns both a realtime prediction and
    the scheduled time, so we prefer the prediction and fall back to schedule
    when a vehicle is not transmitting.
    """
    token, err = bus_token(config)
    if not token:
        return [], err

    resp = http.post(
        "%s/getBusDV" % BUS_API,
        form_body = {
            "token": token,
            "stop": stop_code,
            "route": "",
            "direction": "",
            "ip": "",
        },
        form_encoding = "multipart/form-data",
        ttl_seconds = TTL_REALTIME,
    )
    if resp.status_code != 200:
        return [], "api error"

    body = resp.json()

    # A stale or revoked token shows up as an auth complaint rather than an
    # HTTP error, so drop the cached token and let the next render re-auth.
    if type(body) == "dict" and body.get("message"):
        msg = str(body.get("message")).lower()
        if "token" in msg or "auth" in msg:
            forget_bus_token(config)
            return [], "auth expired"

    trips = body.get("DVTrip", []) if type(body) == "dict" else []
    if not trips:
        return [], "no departures"

    out = []
    for t in trips:
        route = _clean(t.get("public_route")) or "?"

        # departuretime is a wall clock time -- "09:47 PM" -- not a countdown.
        # Reading digits off the front of it would show "9m" for a bus twenty
        # minutes away, so it has to be turned into minutes from now.
        predicted = _clean(t.get("departuretime"))
        scheduled = _clean(t.get("sched_dep_time"))

        wait = minutes_until(predicted, now) if predicted else None
        if wait == None and scheduled:
            wait = minutes_until(scheduled, now)
        if wait == None:
            continue

        # departurestatus carries the operator's own wording, which is where a
        # bus at the kerb says so rather than showing a countdown of zero.
        status = _clean(t.get("departurestatus")).lower()
        if wait <= 0 or status.find("due") >= 0 or status.find("arriv") >= 0:
            when = "now"
        else:
            when = "%d min" % wait

        out.append({
            "route": route,
            "dest": clean_bus_dest(_clean(t.get("header")), route),
            "when": when,
            "live": predicted != "",
            "wait": wait,
        })
        if len(out) >= SCAN_LIMIT:
            break

    if not out:
        return [], "no departures"

    # The feed groups by route rather than ordering by time: stop 21923 has
    # returned a 158 at 6:10 PM ahead of a 159 at 6:01 PM. Taking it as given
    # meant a sooner bus on a later-listed route could be pushed off the
    # screen by a route that happened to come first, which is also why the
    # scan limit is applied before this sort rather than after -- a busy stop
    # returns 25 trips, and cutting at 15 in feed order could drop a whole
    # route before it was ever compared.
    out = sorted(out, key = lambda dep: dep["wait"])
    return out[:FETCH_LIMIT], None

def minutes_until(text, now):
    """Minutes from now to a clock time like "09:47 PM".

    Also accepts the dated form the feed uses for scheduled times,
    "09/27/2026 09:45:58 PM". Returns None when the text is not a time.
    """
    pieces = text.strip().split(" ")
    if len(pieces) == 3:
        pieces = pieces[1:]  # drop a leading date
    if not pieces:
        return None

    parts = pieces[0].split(":")
    if len(parts) < 2:
        return None
    if not parts[0].isdigit() or not parts[1].isdigit():
        return None

    hour = int(parts[0]) % 12
    minute = int(parts[1])
    if len(pieces) > 1 and pieces[1].upper() == "PM":
        hour += 12

    wait = (hour * 60 + minute) - (now.hour * 60 + now.minute)

    # A departure shortly after midnight reads as far in the past. Anything
    # more than two hours behind is tomorrow, not a bus that has left.
    if wait < -120:
        wait += 24 * 60
    return wait

def clean_bus_dest(header, route):
    """'158 NEW YORK  VIA RIVER ROAD' -> 'New York'.

    The live feed repeats the route number the badge already shows and appends
    the routing, the same way GTFS headsigns do. Both are noise on a 64 pixel
    row, and stripping them also makes the direction filter compare like with
    like.
    """
    text = header.strip()

    words = text.split(" ")
    if words and route:
        head = words[0].upper()
        upper_route = route.upper()
        if head == upper_route or (head.startswith(upper_route) and
                                   head[len(route):].isalpha()):
            text = " ".join(words[1:])

    cut = text.upper().find(" VIA ")
    if cut >= 0:
        text = text[:cut]

    # The feed doubles spaces where it drops a field.
    for _ in range(4):
        text = text.replace("  ", " ")

    return pretty_dest(text.strip())

def _clean(value):
    if value == None:
        return ""
    return str(value).strip()

# Long words the realtime feed spells out but a 64px row cannot afford. Light
# rail gets the same treatment at build time; bus destinations arrive live, so
# they have to be shortened here.
DEST_ABBREV = [
    ("Port Authority", "PABT"),
    ("Transportation Center", "Trans Ctr"),
    ("Transportation", "Trans"),
    ("Terminal", "Term"),
    ("Station", "Sta"),
    ("Boulevard", "Blvd"),
    ("Parkway", "Pkwy"),
    ("Highway", "Hwy"),
    ("Avenue", "Ave"),
    ("Street", "St"),
]

# Starlark's title() capitalises after a digit, turning "60TH" into "60Th".
# Every ordinal that can follow a digit, put back.
ORDINAL_FIXES = [
    ["0Th", "0th"],
    ["1Th", "1th"],
    ["2Th", "2th"],
    ["3Th", "3th"],
    ["4Th", "4th"],
    ["5Th", "5th"],
    ["6Th", "6th"],
    ["7Th", "7th"],
    ["8Th", "8th"],
    ["9Th", "9th"],
    ["1St", "1st"],
    ["2Nd", "2nd"],
    ["3Rd", "3rd"],
]

def pretty_dest(text):
    """'NEWARK PENN STATION' -> 'Newark Penn Sta'.

    The API shouts every destination. Title case is both more legible and
    narrower, since capitals are the widest glyphs in the font.
    """
    if not text:
        return ""
    out = text.title()
    for pair in ORDINAL_FIXES:
        out = out.replace(pair[0], pair[1])
    for pair in DEST_ABBREV:
        out = out.replace(pair[0], pair[1])
    return out

# ---------------------------------------------------------------------------
# Scheduled light rail departures
# ---------------------------------------------------------------------------

def scheduled_departures(kind, stop_id, now):
    """Next departures from a published timetable.

    Neither light rail nor NY Waterway's ferries publish realtime data, so both
    read from GTFS timetables precomputed into this app's data files. The only
    difference is which directory they live in.
    """
    tt = http.get("%s/%s/%s.json" % (DATA_BASE, kind, stop_id), ttl_seconds = TTL_STATIC)
    cal = http.get("%s/%s/calendar.json" % (DATA_BASE, kind), ttl_seconds = TTL_STATIC)
    if tt.status_code != 200 or cal.status_code != 200:
        return [], "no data"

    table = tt.json()
    calendar = cal.json()

    today = now.format("20060102")
    services = calendar.get(today, [])
    if not services:
        return [], "no service"

    heads = table.get("heads", [])
    now_min = now.hour * 60 + now.minute

    # GTFS expresses trips running past midnight as hours >= 24, so a 00:20
    # departure is stored as 24:20 under the *previous* day's service. Look at
    # yesterday's services too, shifted back a day, to catch those.
    yesterday = (now - time.parse_duration("24h")).format("20060102")

    upcoming = []
    for (svc_list, offset) in [(services, 0), (calendar.get(yesterday, []), -1440)]:
        for svc in svc_list:
            for dep in table.get("svc", {}).get(svc, []):
                mins = _hhmm_to_minutes(dep[0]) + offset
                if mins == None or mins < now_min:
                    continue
                wait = mins - now_min
                if wait > 180:  # nothing useful beyond three hours out
                    continue

                # json.decode yields numbers as floats; list indices must be int.
                idx = int(dep[2])
                upcoming.append({
                    "route": dep[1],
                    "dest": heads[idx] if idx < len(heads) else "",
                    "when": "%d min" % wait if wait > 0 else "now",
                    "live": False,
                })

    if not upcoming:
        return [], "no departures"

    upcoming = sorted(upcoming, key = lambda d: _wait_of(d))
    return upcoming[:FETCH_LIMIT], None

def _wait_of(dep):
    if dep["when"] == "now":
        return 0
    return int(dep["when"].split(" ")[0])

def _hhmm_to_minutes(hhmm):
    parts = hhmm.split(":")
    if len(parts) != 2:
        return None
    return int(parts[0]) * 60 + int(parts[1])

# ---------------------------------------------------------------------------
# Destination filtering
# ---------------------------------------------------------------------------

# A dropdown option's value cannot be empty and a dropdown must carry a
# default, so an unused slot needs a sentinel rather than "".
SLOT_UNUSED = "off"

# Words too generic to identify a destination on their own.
FILLER = {
    "ST": True,
    "AVE": True,
    "RD": True,
    "DR": True,
    "BLVD": True,
    "PKWY": True,
    "HWY": True,
    "THE": True,
    "AND": True,
    "VIA": True,
    "TO": True,
    "OF": True,
}

def _tokens(text):
    """Split a destination into comparable words, dropping filler."""
    out = []
    cur = ""
    upper = text.upper()
    for i in range(len(upper) + 1):
        ch = upper[i] if i < len(upper) else " "
        if ch.isalnum():
            cur += ch
        else:
            if len(cur) >= 2 and cur not in FILLER:
                out.append(cur)
            cur = ""
    return out

# Abbreviations the two sources disagree about. Expanding both sides to a
# canonical form is safer than matching on prefixes, which would happily pair
# "Newark" with "New York".
CANONICAL = {
    "SQ": "SQUARE",
    "TERM": "TERMINAL",
    "STA": "STATION",
    "STN": "STATION",
    "CTR": "CENTER",
    "CENT": "CENTER",
    "CENTRE": "CENTER",
    "PK": "PARK",
    "HTS": "HEIGHTS",
    "EXP": "EXPRESS",
    "EXPY": "EXPRESS",
    "JCT": "JUNCTION",
    "TRANSP": "TRANSPORTATION",
    "UNIV": "UNIVERSITY",
    "HOSP": "HOSPITAL",
    "MED": "MEDICAL",
}

def _canonical(token):
    return CANONICAL.get(token, token)

def _token_match(a, b):
    """Equal once abbreviations are expanded ("Sq" and "Square")."""
    return _canonical(a) == _canonical(b)

def matches_destination(dep_dest, wanted):
    """Is this departure heading where the user asked?

    The live feed and the timetable describe the same place with different
    amounts of detail -- "Journal Square" against "Jersey City Journal Sq", or
    "Montgomery St" against the full "Montgomery St West Side Ave Society
    Hill". So compare against whichever description is shorter and require all
    of its words to appear in the other, abbreviations allowed.

    At least one substantial word must match, so two destinations do not pair
    up on nothing but "St" and "Ave".
    """
    a = _tokens(dep_dest)
    b = _tokens(wanted)
    if not a or not b:
        return False

    need = b if len(b) <= len(a) else a
    have = a if len(b) <= len(a) else b

    strong = False
    for t in need:
        found = False
        for h in have:
            if _token_match(t, h):
                found = True
                if len(t) >= 4:
                    strong = True
                break
        if not found:
            return False
    return strong

def filter_by_direction(departures, terminals):
    """Keep only departures heading the chosen way.

    A direction is a set of terminals, not one place -- the 159 outbound
    reaches Fort Lee, Cliffside Park and Fairview, and all three mean the same
    way -- so a departure counts if it matches any of them.
    """
    if type(terminals) != "list" or not terminals:
        return departures

    kept = []
    for dep in departures:
        for terminal in terminals:
            if matches_destination(dep["dest"], terminal):
                kept.append(dep)
                break

    if not kept:
        return "none to %s" % terminals[0]
    return kept

def fetch_destinations(stop, code = None):
    """Destinations served from a stop, for the direction picker.

    A grouped bus stop asks about each of its member codes in turn. They all
    sit in the same grid cell, so this is one download however many are asked
    for -- http.get caches it.
    """
    key = cell_key(stop["lat"], stop["lon"]) if "lat" in stop else None
    if not key:
        return []
    resp = http.get("%s/dirs/%s.json" % (DATA_BASE, key), ttl_seconds = TTL_STATIC)
    if resp.status_code != 200:
        return []
    return resp.json().get(code if code else stop["c"], [])

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def badge_color(stop, route):
    if stop["m"] == "l":
        return LINE_COLORS.get(route, "#4aa3df")
    if stop["m"] == "f":
        return FERRY_COLOR
    return BUS_COLOR

def text_on(hex_color):
    """Black or white label, whichever survives on this background.

    The River LINE's official navy would swallow black text, while the bus
    amber would swallow white, so pick per color rather than guessing once.
    """
    r = int(hex_color[1:3], 16)
    g = int(hex_color[3:5], 16)
    b = int(hex_color[5:7], 16)
    luminance = (r * 299 + g * 587 + b * 114) // 1000
    return "#000000" if luminance > 140 else "#ffffff"

def _leading_digits(s):
    """First run of digits in a string. Starlark strings are not iterable."""
    out = ""
    for i in range(len(s)):
        ch = s[i]
        if ch.isdigit():
            out += ch
        elif out:
            break
    return out

def wait_color(when, live):
    """Red when you need to run, green when you have time.

    Dimmed when the time came from a timetable rather than a vehicle being
    tracked -- which is every light rail and ferry departure, since neither
    publishes realtime this app can read, and any bus not transmitting.
    """
    soon = when.lower() in ("now", "due", "arriving")
    if not soon:
        digits = _leading_digits(when)
        soon = digits != "" and int(digits) <= 3

    if soon:
        return COLOR_SOON if live else COLOR_SOON_SCHEDULED
    return COLOR_OK if live else COLOR_OK_SCHEDULED

# tom-thumb glyphs are 3px wide with 1px of spacing.
CHAR_W = 4
WAIT_W = 13

# "LIVE" needs four characters, wider than most route numbers, so a flashing
# badge is widened to fit rather than letting the row jump about mid-cycle.
LIVE_LABEL = "LIVE"
LIVE_W = CHAR_W * 4 + 3  # fits "now" and up to two digits plus the "m"

def fit_text(text, width):
    """Show text in a fixed width, scrolling it when it does not fit.

    A Box centres its child, so text wider than the box overflows at both ends
    and you read its middle -- "Midtown / W. 39th St." shows up as
    "wn / W. 39th". Short text is left-aligned by padding the remainder; long
    text scrolls instead, so the whole name is readable eventually.
    """
    if CHAR_W * len(text) > width:
        return render.Marquee(
            width = width,
            child = render.Text(content = text, font = FONT, color = COLOR_TEXT),
        )

    pad = width - CHAR_W * len(text)
    children = [render.Text(content = text, font = FONT, color = COLOR_TEXT)]
    if pad > 0:
        children.append(render.Box(width = pad, height = 7))
    return render.Row(children = children)

def watch_line(item):
    """One watched stop as a single row: route badge, where it goes, minutes.

    The stop itself is deliberately not shown. Four rows of "Blvd East at 47th
    St" would fill the screen with names already known -- what changes, and
    what is worth a glance, is where the next one goes and how long it is away.
    """
    stop = item["stop"]
    dep = item["dep"]

    if not dep:
        return (render.Row(
            cross_align = "center",
            children = [
                render.Box(width = 3, height = 7, color = badge_color(stop, "")),
                render.Box(width = 2, height = 7),
                fit_text(item["err"] or "no service", 59),
            ],
        ), False)

    route = dep["route"]
    live = dep.get("live", False)

    badge_w = min(CHAR_W * len(route) + 3, 26) if route else 3
    if route and live:
        badge_w = max(badge_w, LIVE_W)

    # One pixel each side of the destination, or it collides with the
    # countdown and reads as "New York10m".
    dest_w = 64 - badge_w - 2 - WAIT_W

    color = badge_color(stop, route)
    if not route:
        # Ferries have no useful route name -- the route is its destination --
        # so the badge shrinks to a plain colour stripe.
        badge = render.Box(width = badge_w, height = 7, color = color)
    elif live:
        badge = live_badge(route, color, badge_w)
    else:
        badge = render.Box(
            width = badge_w,
            height = 7,
            color = color,
            child = render.Text(
                content = route,
                font = FONT,
                color = text_on(color),
            ),
        )

    # A row moves if its destination is too long to sit still, or if its
    # badge is flashing.
    scrolls = CHAR_W * len(dep["dest"]) > dest_w
    row = render.Row(
        cross_align = "center",
        children = [
            badge,
            render.Box(width = 1, height = 7),
            fit_text(dep["dest"], dest_w),
            render.Box(width = 1, height = 7),
            render.Box(
                width = WAIT_W,
                height = 7,
                child = render.Text(
                    content = _short_wait(dep["when"]),
                    font = FONT,
                    color = wait_color(dep["when"], live),
                ),
            ),
        ],
    )
    return (row, scrolls or live)

def live_badge(route, color, width):
    """A route badge that briefly says LIVE, for a vehicle being tracked.

    Built as its own Animation. Sequence, which drives the paging, plays each
    page's animations rather than freezing them, so this keeps cycling
    alongside a scrolling destination.
    """
    on_route = render.Box(
        width = width,
        height = 7,
        color = color,
        child = render.Text(content = route, font = FONT, color = text_on(color)),
    )
    on_live = render.Box(
        width = width,
        height = 7,
        color = COLOR_TEXT,
        child = render.Text(content = LIVE_LABEL, font = FONT, color = "#000000"),
    )

    frames = []
    for _ in range(LIVE_FLASH_OFF):
        frames.append(on_route)
    for _ in range(LIVE_FLASH_ON):
        frames.append(on_live)
    return render.Animation(children = frames)

def _short_wait(when):
    """'12 min' -> '12'. The column is too narrow to spell it out."""
    w = when.strip()
    if w.lower() in ("now", "due", "arriving"):
        return "now"
    digits = _leading_digits(w)
    if digits:
        return digits + "m"
    return w[:5]

def page_of(items):
    """One screen of watched stops, plus whether anything on it moves."""
    rows = []
    animated = False
    for item in items:
        line, moves = watch_line(item)
        rows.append(line)
        rows.append(render.Box(height = 1))
        animated = animated or moves
    return (render.Column(children = rows), animated)

def message_screen(text):
    return render.Root(
        child = render.Box(
            child = render.WrappedText(
                content = text,
                font = FONT,
                color = COLOR_DIM,
                align = "center",
            ),
        ),
    )

def unwrap_stop(raw):
    """Decode a stop value, tolerating pixlet's selection envelope.

    A LocationBased selection does not arrive as the string put in
    schema.Option.value; pixlet wraps it as {"display": ..., "value": ...}, so
    the real payload is one decode deeper.
    """
    if not raw or raw == SLOT_UNUSED:
        return json.decode(DEFAULT_STOP)

    stop = json.decode(raw)
    if type(stop) == "dict" and "m" not in stop and "value" in stop:
        stop = json.decode(stop["value"])

    # Anything unrecognisable falls back rather than crashing the render.
    if type(stop) != "dict" or "m" not in stop or "c" not in stop:
        return json.decode(DEFAULT_STOP)
    return stop

def stop_configured(raw):
    """Has this slot actually been given a stop?"""
    if not raw or raw == SLOT_UNUSED:
        return False
    decoded = json.decode(raw)
    if type(decoded) == "dict" and "value" in decoded and "m" not in decoded:
        decoded = json.decode(decoded["value"])
    return type(decoded) == "dict" and "c" in decoded and "m" in decoded

def configured_slots(config):
    """The slots that have been filled in, in the order they appear."""
    out = []
    for slot in range(1, SLOTS + 1):
        raw = config.get("stop%d" % slot)
        if not stop_configured(raw):
            continue
        out.append({"stop": unwrap_stop(raw)})
    return out

def next_departures(slot, now, count, config):
    """The soonest departures for one watched stop, after its direction filter.

    Asks for `count` because the screen holds four rows however many stops are
    being watched: one stop fills them with its own next four, two stops take
    two each. Leaving the bottom half black wastes the only space there is.
    """
    stop = slot["stop"]
    if stop["m"] == "l":
        departures, err = scheduled_departures("lr", stop["c"], now)
    elif stop["m"] == "f":
        departures, err = scheduled_departures("fr", stop["c"], now)
    else:
        departures, err = bus_departures(stop["c"], now, config)

    if err:
        return [{"stop": stop, "dep": None, "err": err}]

    filtered = filter_by_direction(departures, stop.get("d", []))
    if type(filtered) == "string":
        return [{"stop": stop, "dep": None, "err": "none that way"}]
    if not filtered:
        return [{"stop": stop, "dep": None, "err": "no departures"}]

    out = []
    for dep in filtered[:count]:
        out.append({"stop": stop, "dep": dep, "err": None})
    return out

def main(config):
    # Every time this app compares against is published in the agency's own
    # timezone: NJ Transit and NY Waterway both declare America/New_York in
    # their GTFS. Using the device's timezone instead would put a Tidbyt
    # outside Eastern hours out by exactly that offset -- countdowns wrong, and
    # the service calendar looked up for the wrong day near midnight.
    now = time.now().in_location(AGENCY_TZ)

    slots = configured_slots(config)
    if not slots:
        return message_screen("pick a stop")

    items = []
    if len(slots) >= LINES_PER_PAGE:
        # Every row is spoken for; one departure each, and page through them.
        for slot in slots:
            items.extend(next_departures(slot, now, 1, config))
    else:
        # Fewer stops than rows, so hand out the spare rows rather than
        # leaving the bottom of the screen black. Earlier slots get the
        # remainder, since they were chosen first.
        each = LINES_PER_PAGE // len(slots)
        spare = LINES_PER_PAGE % len(slots)
        for i, slot in enumerate(slots):
            want = each + (1 if i < spare else 0)
            got = next_departures(slot, now, want, config)

            # A stop with nothing to show still only needs its one line; give
            # what it did not use back to the others.
            items.extend(got)

    pages = []
    for start in range(0, len(items), LINES_PER_PAGE):
        pages.append(page_of(items[start:start + LINES_PER_PAGE]))

    # Only a page with nothing moving needs padding out; wrapping one that
    # does animate would freeze it.
    pages = [page if animated else hold(page) for (page, animated) in pages]

    if len(pages) == 1:
        return render.Root(
            delay = DELAY_MS,
            max_age = MAX_AGE,
            show_full_animation = True,
            child = pages[0],
        )

    # Sequence, not Animation. Animation treats every child as exactly one
    # frame, which freezes any scrolling or flashing inside a page -- measured
    # at 40 frames where the content needed 171. Sequence plays each child's
    # own animation through before moving on.
    return render.Root(
        delay = DELAY_MS,
        max_age = MAX_AGE,
        show_full_animation = True,
        child = render.Sequence(children = pages),
    )

def hold(page):
    """Keep a page up long enough to read even when nothing on it moves.

    Sequence gives a child as many frames as it animates for, and a page of
    static rows animates for exactly one. Repeating it supplies the duration.
    """
    frames = []
    for _ in range(PAGE_HOLD_MS // DELAY_MS):
        frames.append(page)
    return render.Animation(children = frames)

def decode_location(location):
    """The source field's value as a dict, or None if it has not been set.

    Tidbyt's config UI only calls a generated handler once its source field
    holds a value, so this always used to be a populated address. Tronbyt's
    server calls the handler as soon as the config page loads, which hands it
    an empty string. Decoding that raises, the handler dies, and because these
    dropdowns are the handler's only output, no stop can ever be picked.

    The value also arrives wrapped in its own JSON envelope in some cases,
    the same way a configured slot does -- see stop_configured().
    """
    if not location:
        return None

    decoded = json.decode(location)
    if type(decoded) == "dict" and "value" in decoded and "lat" not in decoded:
        decoded = json.decode(decoded["value"])
    if type(decoded) != "dict" or "lat" not in decoded:
        return None
    return decoded

def stop_options(location, mode = ""):
    """Nearby stops, one option per direction of travel.

    Direction is baked into the option rather than offered as a second field.
    A schema.Generated can only source from a *statically declared* field, and
    these dropdowns are themselves generated -- pixlet rejects the schema with
    "references source that does not exist: stop1". So each option has to be
    self-contained: which stop to query, and which way it is going.

    This runs on Tidbyt's servers when someone configures the app, not on the
    device, so it can afford to download a grid cell and sort it.
    """
    loc = decode_location(location)
    if not loc:
        return []
    lat = float(loc["lat"])
    lon = float(loc["lng"])

    options = []
    for (dist_km, stop) in nearby_stops(lat, lon, mode):
        stop_mode = stop.get("m", "b")

        # Starlark's % operator has no precision specifier, so round by hand.
        tenths = int(dist_km * 0.621371 * 10 + 0.5)
        miles = "%d.%d" % (tenths // 10, tenths % 10)

        routes = ", ".join(stop.get("r", [])[:4])
        suffix = " - %s" % routes if routes and stop_mode != "f" else ""

        for entry in stop_directions(stop):
            label = MODE_TAGS.get(stop_mode, "BUS") + MODE_SEPARATOR + stop["n"]
            if entry["l"]:
                label += " to %s" % entry["l"]

            options.append(
                schema.Option(
                    display = "%s%s (%s mi)" % (label, suffix, miles),
                    value = json.encode({
                        "c": stop["c"],
                        "m": stop_mode,
                        "d": entry["m"],
                    }),
                ),
            )

    if not options:
        options.append(
            schema.Option(
                display = "Nothing found nearby",
                value = SLOT_UNUSED,
            ),
        )
    return options

def stop_directions(stop):
    """Every way a rider can leave this stop, as {l: label, m: terminals}.

    Falls back to a single unlabelled entry when a stop has no direction data,
    so it still appears rather than vanishing.
    """
    entries = fetch_destinations(stop)
    if not entries:
        return [{"l": stop.get("t", ""), "m": []}]
    return entries

def stop_fields(location):
    """Every slot's dropdown, built from the one address.

    All six come from a single generated field on purpose. Pixlet's config UI
    keys a generated field by its `source`, so six of them sourced from the
    same address collapse into one -- whichever reply arrives last is the only
    slot that appears. A handler may return several fields, which sidesteps
    that entirely and computes the nearby list once instead of six times.
    """
    if not decode_location(location):
        # No address yet. Returning no fields leaves the form showing just the
        # location picker; the dropdowns appear once it is filled in.
        return []

    options = [schema.Option(display = "Not used", value = SLOT_UNUSED)]
    options.extend(stop_options(location))

    fields = []
    for slot in range(1, SLOTS + 1):
        fields.append(
            schema.Dropdown(
                id = "stop%d" % slot,
                name = "Stop %d" % slot,
                desc = "Nearest first. Leave as Not used to skip.",
                icon = "route",
                default = SLOT_UNUSED,
                options = options,
            ),
        )
    return fields

def get_schema():
    """One address, then six stop slots shown in the order they are filled in.

    The address is a single schema.Location. Each slot is a dropdown generated
    from it, so nearby stops are computed once per location rather than asking
    for the same address six times over.

    Pixlet builds its handler table from this static schema and keys it by
    field id, so a handler that only appears on a *generated* field is never
    registered -- requesting its options answers "no exported handler named
    ...". Generated fields may therefore return dropdowns, which carry no
    handler, but not a LocationBased, which does.
    """
    return schema.Schema(
        version = "1",
        fields = [
            schema.Location(
                id = "home",
                name = "Location",
                desc = "Your address. Everything below is measured from here.",
                icon = "locationDot",
            ),
            schema.Generated(
                id = "stop_pickers",
                source = "home",
                handler = stop_fields,
            ),
            schema.Text(
                id = "njt_user",
                name = "NJ Transit username",
                desc = "Free account from developer.njtransit.com. Live bus times need it; light rail does not.",
                icon = "user",
            ),
            schema.Text(
                id = "njt_pass",
                name = "NJ Transit password",
                desc = "Held by whichever server runs this app. Pixlet has no masked field, so it is typed in the clear.",
                icon = "key",
            ),
        ],
    )
