"""
Applet: NJ Transit Nearby
Summary: Nearby NJT departures
Description: Pick a spot on the map and see the next departures from the closest
             NJ Transit bus stop or light rail station. Bus times are realtime
             (GPS-based); light rail times come from the published timetable.
Author: joshbrewster42
"""

load("cache.star", "cache")
load("encoding/json.star", "json")
load("http.star", "http")
load("math.star", "math")
load("render.star", "render")
load("schema.star", "schema")
load("secret.star", "secret")
load("time.star", "time")

# ---------------------------------------------------------------------------
# Static data, generated by pipeline/build_index.py
# ---------------------------------------------------------------------------
#
# A Tidbyt app is a single sandboxed file with no filesystem, so the stop index
# lives in this app's repo and is fetched over HTTP. Stops are bucketed into
# 0.1-degree grid cells so that finding "stops near me" costs one small
# download instead of an index of 16.5k bus stops.
#
# Repoint this at your own fork if you regenerate the data.
DATA_BASE = "https://raw.githubusercontent.com/joshbrewster42/tidbyt-nj-transit/main/data/v1"

CELL_SIZE = 0.1  # must match CELL_SIZE in pipeline/build_index.py

# Static data changes only when NJ Transit publishes a new booking, so cache it
# hard. Realtime predictions obviously cannot be.
TTL_STATIC = 86400
TTL_REALTIME = 30

# A countdown goes wrong quietly. If the device loses connectivity it keeps
# showing whatever it last received, so a "3 min" can sit on screen long after
# that bus has gone -- worse than showing nothing, because it is still
# believable. max_age tells the device to stop displaying this render once it
# is this old.
MAX_AGE = 120

# ---------------------------------------------------------------------------
# NJ Transit realtime bus API
# ---------------------------------------------------------------------------
#
# Registration: https://developer.njtransit.com/registration/
#
# Auth is a username/password exchange, not a bare API key: POST credentials to
# authenticateUser, get back a UserToken good for roughly 24 hours, then pass
# that token to the data endpoints. We cache the token so a device refreshing
# every 15 seconds is not re-authenticating constantly.
BUS_API = "https://pcsdata.njtransit.com/api/BUSDV2"
TOKEN_CACHE_KEY = "njt_bus_token_v1"
TOKEN_TTL = 20 * 60 * 60  # refresh well before the ~24h expiry

# Credentials, encrypted with `pixlet encrypt`. Only Tidbyt's servers hold the
# key that reverses this, so these are safe to commit; secret.decrypt() returns
# None when running locally, which the code below treats as "no realtime".
#
#   pixlet encrypt nj-transit-nearby '<your njtransit username>'
#   pixlet encrypt nj-transit-nearby '<your njtransit password>'
#
# Paste each result here, replacing the placeholders.
NJT_USERNAME_ENC = "REPLACE_WITH_PIXLET_ENCRYPT_OUTPUT_USERNAME"
NJT_PASSWORD_ENC = "REPLACE_WITH_PIXLET_ENCRYPT_OUTPUT_PASSWORD"

# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------
# Six numbered slots. A Tidbyt schema is a static form with no "add another",
# so the number of things that can be watched has to be fixed up front.
SLOTS = 6

# With no header, four 7px lines fit on a 32px display. More than four watched
# stops pages between screens.
LINES_PER_PAGE = 4

# A page holds for this long before the next one. At DELAY_MS per frame that is
# PAGE_HOLD_MS / DELAY_MS copies of the same widget, because render.Animation
# treats every child as exactly one frame.
DELAY_MS = 100
PAGE_HOLD_MS = 4000

# Fetch more than fits, so filtering by destination still has something to
# choose from. Only the soonest is shown, but the filter needs candidates.
FETCH_LIMIT = 15

# Official NJ Transit route colors, from routes.txt in the GTFS feed.
LINE_COLORS = {
    "HBLR": "#008080",
    "NLR": "#009ad1",
    "RVLN": "#1a1aff",  # feed says 00008B, lifted for legibility on a dark LED
}
BUS_COLOR = "#e8a33d"

# NY Waterway's hull blue. NJ Transit runs no ferries -- the Hudson crossings
# are NY Waterway's, and their feed is a separate source.
FERRY_COLOR = "#1e9bd7"

COLOR_DIM = "#6a6a6a"
COLOR_TEXT = "#ffffff"
COLOR_SOON = "#ff5656"
COLOR_OK = "#4ade80"

FONT = "tom-thumb"

MODE_NAMES = {"b": "Bus", "l": "Light Rail", "f": "Ferry"}

# Leading badges for the stop picker. Every entry gets one, including buses:
# tagging only the exceptions means the common case carries no marker at all,
# and a list where most rows look identical is a list nobody can scan.
MODE_TAGS = {"b": "BUS", "l": "RAIL", "f": "FERRY"}

# The badge needs a visible separator. Padding it out with spaces does not
# work -- the picker renders as HTML, which collapses runs of whitespace, so
# "BUS  Park Ave" arrives as "BUS Park Ave" and reads as one phrase. The
# middle dot also stays clear of the " - " already used before the route list.
MODE_SEPARATOR = " \u00b7 "

# A floor, not a quota: at least this many light rail stations and ferry
# terminals always make the picker, however far down a distance ranking they
# fall, because bus stops are dense enough to bury a whole mode. Anything
# genuinely close still appears on its own merit. Keeping this at one avoids
# dragging in a second terminal across the river just to fill a slot.
MODE_GUARANTEE = 1

DEFAULT_STOP = json.encode({
    "c": "20783",
    "n": "Hoboken Ave at Summit Ave",
    "m": "b",
    "r": ["119"],
})

# ---------------------------------------------------------------------------
# Geography
# ---------------------------------------------------------------------------

def cell_key(lat, lon):
    """Grid cell containing a point. Mirrors cell_key() in build_index.py."""
    return "%d_%d" % (math.floor(lat / CELL_SIZE), math.floor(lon / CELL_SIZE))

def haversine_km(lat1, lon1, lat2, lon2):
    """Great-circle distance. Good enough for ranking stops a few km apart."""
    r = 6371.0
    p1 = math.radians(lat1)
    p2 = math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) * math.sin(dp / 2) + \
        math.cos(p1) * math.cos(p2) * math.sin(dl / 2) * math.sin(dl / 2)
    return 2 * r * math.atan2(math.sqrt(a), math.sqrt(1 - a))

def fetch_cell(key):
    """Stops in one grid cell, or [] if the cell has none (most of them)."""
    resp = http.get("%s/cells/%s.json" % (DATA_BASE, key), ttl_seconds = TTL_STATIC)
    if resp.status_code != 200:
        return []
    return resp.json()

def nearby_stops(lat, lon, mode = "", limit = 24):
    """Stops near a point, nearest first.

    Fetches the cell containing the point plus the three cells adjacent to
    whichever corner the point sits closest to. That covers the neighbourhood
    without paying for a full 3x3 block, and a cell is ~11km tall so a point
    near an edge still sees across it.
    """
    ci = math.floor(lat / CELL_SIZE)
    cj = math.floor(lon / CELL_SIZE)

    # Which way does the point lean inside its own cell?
    di = 1 if (lat / CELL_SIZE - ci) >= 0.5 else -1
    dj = 1 if (lon / CELL_SIZE - cj) >= 0.5 else -1

    candidates = []
    for (i, j) in [(ci, cj), (ci + di, cj), (ci, cj + dj), (ci + di, cj + dj)]:
        candidates.extend(fetch_cell("%d_%d" % (i, j)))

    scored = []
    for s in candidates:
        # Filter before ranking, or asking for ferries would return the 24
        # nearest stops of any kind and then keep whichever happened to float.
        if mode and s["m"] != mode:
            continue
        scored.append((haversine_km(lat, lon, s["lat"], s["lon"]), s))
    scored = sorted(scored, key = lambda pair: pair[0])

    if mode:
        # One mode is already its own group; nothing can be crowded out.
        return scored[:limit]
    return guarantee_modes(scored, limit)

def guarantee_modes(scored, limit):
    """Nearest stops, but never with a whole mode crowded out.

    Bus stops are dense: from a spot a few blocks inland of Weehawken there are
    two dozen within 0.4 miles, which is enough to push the ferry terminal half
    a mile away off a distance-ranked list entirely. Somebody who wants the
    ferry then cannot find it at all.

    So take the nearest stops as usual, then make sure the closest few light
    rail stations and ferry terminals are in there regardless of where they
    placed, and re-sort so the list still reads by distance.
    """
    chosen = scored[:limit]

    seen = {}
    for (_d, s) in chosen:
        seen[s["m"] + s["c"]] = True

    for mode in ["l", "f"]:
        present = 0
        for (_d, s) in chosen:
            if s["m"] == mode:
                present += 1

        for (dist, s) in scored:
            if present >= MODE_GUARANTEE:
                break
            if s["m"] != mode or seen.get(s["m"] + s["c"]):
                continue
            chosen.append((dist, s))
            seen[s["m"] + s["c"]] = True
            present += 1

    return sorted(chosen, key = lambda pair: pair[0])

# ---------------------------------------------------------------------------
# Realtime bus departures
# ---------------------------------------------------------------------------

def bus_token():
    """A UserToken for the bus API, cached across renders."""
    cached = cache.get(TOKEN_CACHE_KEY)
    if cached:
        return cached

    username = secret.decrypt(NJT_USERNAME_ENC)
    password = secret.decrypt(NJT_PASSWORD_ENC)
    if not username or not password:
        # secret.decrypt returns None outside the Tidbyt cloud, which is the
        # normal case when developing locally.
        return None

    resp = http.post(
        "%s/authenticateUser" % BUS_API,
        form_body = {"username": username, "password": password},
        form_encoding = "application/x-www-form-urlencoded",
    )
    if resp.status_code != 200:
        return None

    body = resp.json()
    token = body.get("UserToken")
    if not token or body.get("Authenticated") not in ("True", True, "true"):
        return None

    cache.set(TOKEN_CACHE_KEY, token, ttl_seconds = TOKEN_TTL)
    return token

def bus_departures(stop_code):
    """Next buses from a stop, as a list of display rows.

    Returns (departures, error). The API returns both a realtime prediction and
    the scheduled time, so we prefer the prediction and fall back to schedule
    when a vehicle is not transmitting.
    """
    token = bus_token()
    if not token:
        return [], "no api key"

    resp = http.post(
        "%s/getBusDV" % BUS_API,
        form_body = {
            "token": token,
            "stop": stop_code,
            "route": "",
            "direction": "",
            "ip": "",
        },
        form_encoding = "multipart/form-data",
        ttl_seconds = TTL_REALTIME,
    )
    if resp.status_code != 200:
        return [], "api error"

    body = resp.json()

    # A stale or revoked token shows up as an auth complaint rather than an
    # HTTP error, so drop the cached token and let the next render re-auth.
    if type(body) == "dict" and body.get("message"):
        msg = str(body.get("message")).lower()
        if "token" in msg or "auth" in msg:
            cache.set(TOKEN_CACHE_KEY, "", ttl_seconds = 1)
            return [], "auth expired"

    trips = body.get("DVTrip", []) if type(body) == "dict" else []
    if not trips:
        return [], "no departures"

    out = []
    for t in trips:
        predicted = _clean(t.get("departuretime"))
        scheduled = _clean(t.get("sched_dep_time"))
        when = predicted or scheduled
        if not when:
            continue
        out.append({
            "route": _clean(t.get("public_route")) or "?",
            "dest": pretty_dest(_clean(t.get("header"))),
            "when": when,
            "live": predicted != "",
        })
        if len(out) >= FETCH_LIMIT:
            break

    if not out:
        return [], "no departures"
    return out, None

def _clean(value):
    if value == None:
        return ""
    return str(value).strip()

# Long words the realtime feed spells out but a 64px row cannot afford. Light
# rail gets the same treatment at build time; bus destinations arrive live, so
# they have to be shortened here.
DEST_ABBREV = [
    ("Port Authority", "PABT"),
    ("Transportation Center", "Trans Ctr"),
    ("Transportation", "Trans"),
    ("Terminal", "Term"),
    ("Station", "Sta"),
    ("Boulevard", "Blvd"),
    ("Parkway", "Pkwy"),
    ("Highway", "Hwy"),
    ("Avenue", "Ave"),
    ("Street", "St"),
]

def pretty_dest(text):
    """'NEWARK PENN STATION' -> 'Newark Penn Sta'.

    The API shouts every destination. Title case is both more legible and
    narrower, since capitals are the widest glyphs in the font.
    """
    if not text:
        return ""
    out = text.title()
    for pair in DEST_ABBREV:
        out = out.replace(pair[0], pair[1])
    return out

# ---------------------------------------------------------------------------
# Scheduled light rail departures
# ---------------------------------------------------------------------------

def scheduled_departures(kind, stop_id, now):
    """Next departures from a published timetable.

    Neither light rail nor NY Waterway's ferries publish realtime data, so both
    read from GTFS timetables precomputed into this app's data files. The only
    difference is which directory they live in.
    """
    tt = http.get("%s/%s/%s.json" % (DATA_BASE, kind, stop_id), ttl_seconds = TTL_STATIC)
    cal = http.get("%s/%s/calendar.json" % (DATA_BASE, kind), ttl_seconds = TTL_STATIC)
    if tt.status_code != 200 or cal.status_code != 200:
        return [], "no data"

    table = tt.json()
    calendar = cal.json()

    today = now.format("20060102")
    services = calendar.get(today, [])
    if not services:
        return [], "no service"

    heads = table.get("heads", [])
    now_min = now.hour * 60 + now.minute

    # GTFS expresses trips running past midnight as hours >= 24, so a 00:20
    # departure is stored as 24:20 under the *previous* day's service. Look at
    # yesterday's services too, shifted back a day, to catch those.
    yesterday = (now - time.parse_duration("24h")).format("20060102")

    upcoming = []
    for (svc_list, offset) in [(services, 0), (calendar.get(yesterday, []), -1440)]:
        for svc in svc_list:
            for dep in table.get("svc", {}).get(svc, []):
                mins = _hhmm_to_minutes(dep[0]) + offset
                if mins == None or mins < now_min:
                    continue
                wait = mins - now_min
                if wait > 180:  # nothing useful beyond three hours out
                    continue

                # json.decode yields numbers as floats; list indices must be int.
                idx = int(dep[2])
                upcoming.append({
                    "route": dep[1],
                    "dest": heads[idx] if idx < len(heads) else "",
                    "when": "%d min" % wait if wait > 0 else "now",
                    "live": False,
                })

    if not upcoming:
        return [], "no departures"

    upcoming = sorted(upcoming, key = lambda d: _wait_of(d))
    return upcoming[:FETCH_LIMIT], None

def _wait_of(dep):
    if dep["when"] == "now":
        return 0
    return int(dep["when"].split(" ")[0])

def _hhmm_to_minutes(hhmm):
    parts = hhmm.split(":")
    if len(parts) != 2:
        return None
    return int(parts[0]) * 60 + int(parts[1])

# ---------------------------------------------------------------------------
# Destination filtering
# ---------------------------------------------------------------------------

# A dropdown option's value cannot be empty, and a dropdown must carry a
# default: pixlet answers "Field validation for 'Value' failed on the
# 'required' tag". So both "no filter" and "slot unused" need real sentinels
# rather than "".
ALL_DIRECTIONS = "all"
SLOT_UNUSED = "off"

# Words too generic to identify a destination on their own.
FILLER = {
    "ST": True,
    "AVE": True,
    "RD": True,
    "DR": True,
    "BLVD": True,
    "PKWY": True,
    "HWY": True,
    "THE": True,
    "AND": True,
    "VIA": True,
    "TO": True,
    "OF": True,
}

def _tokens(text):
    """Split a destination into comparable words, dropping filler."""
    out = []
    cur = ""
    upper = text.upper()
    for i in range(len(upper) + 1):
        ch = upper[i] if i < len(upper) else " "
        if ch.isalnum():
            cur += ch
        else:
            if len(cur) >= 2 and cur not in FILLER:
                out.append(cur)
            cur = ""
    return out

# Abbreviations the two sources disagree about. Expanding both sides to a
# canonical form is safer than matching on prefixes, which would happily pair
# "Newark" with "New York".
CANONICAL = {
    "SQ": "SQUARE",
    "TERM": "TERMINAL",
    "STA": "STATION",
    "STN": "STATION",
    "CTR": "CENTER",
    "CENT": "CENTER",
    "CENTRE": "CENTER",
    "PK": "PARK",
    "HTS": "HEIGHTS",
    "EXP": "EXPRESS",
    "EXPY": "EXPRESS",
    "JCT": "JUNCTION",
    "TRANSP": "TRANSPORTATION",
    "UNIV": "UNIVERSITY",
    "HOSP": "HOSPITAL",
    "MED": "MEDICAL",
}

def _canonical(token):
    return CANONICAL.get(token, token)

def _token_match(a, b):
    """Equal once abbreviations are expanded ("Sq" and "Square")."""
    return _canonical(a) == _canonical(b)

def matches_destination(dep_dest, wanted):
    """Is this departure heading where the user asked?

    The live feed and the timetable describe the same place with different
    amounts of detail -- "Journal Square" against "Jersey City Journal Sq", or
    "Montgomery St" against the full "Montgomery St West Side Ave Society
    Hill". So compare against whichever description is shorter and require all
    of its words to appear in the other, abbreviations allowed.

    At least one substantial word must match, so two destinations do not pair
    up on nothing but "St" and "Ave".
    """
    a = _tokens(dep_dest)
    b = _tokens(wanted)
    if not a or not b:
        return False

    need = b if len(b) <= len(a) else a
    have = a if len(b) <= len(a) else b

    strong = False
    for t in need:
        found = False
        for h in have:
            if _token_match(t, h):
                found = True
                if len(t) >= 4:
                    strong = True
                break
        if not found:
            return False
    return strong

def filter_by_direction(departures, terminals):
    """Keep only departures heading the chosen way.

    A direction is a set of terminals, not one place -- the 159 outbound
    reaches Fort Lee, Cliffside Park and Fairview, and all three mean the same
    way -- so a departure counts if it matches any of them.
    """
    if type(terminals) != "list" or not terminals:
        return departures

    kept = []
    for dep in departures:
        for terminal in terminals:
            if matches_destination(dep["dest"], terminal):
                kept.append(dep)
                break

    if not kept:
        return "none to %s" % terminals[0]
    return kept

def fetch_destinations(stop, code = None):
    """Destinations served from a stop, for the direction picker.

    A grouped bus stop asks about each of its member codes in turn. They all
    sit in the same grid cell, so this is one download however many are asked
    for -- http.get caches it.
    """
    key = cell_key(stop["lat"], stop["lon"]) if "lat" in stop else None
    if not key:
        return []
    resp = http.get("%s/dirs/%s.json" % (DATA_BASE, key), ttl_seconds = TTL_STATIC)
    if resp.status_code != 200:
        return []
    return resp.json().get(code if code else stop["c"], [])

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def badge_color(stop, route):
    if stop["m"] == "l":
        return LINE_COLORS.get(route, "#4aa3df")
    if stop["m"] == "f":
        return FERRY_COLOR
    return BUS_COLOR

def text_on(hex_color):
    """Black or white label, whichever survives on this background.

    The River LINE's official navy would swallow black text, while the bus
    amber would swallow white, so pick per color rather than guessing once.
    """
    r = int(hex_color[1:3], 16)
    g = int(hex_color[3:5], 16)
    b = int(hex_color[5:7], 16)
    luminance = (r * 299 + g * 587 + b * 114) // 1000
    return "#000000" if luminance > 140 else "#ffffff"

def _leading_digits(s):
    """First run of digits in a string. Starlark strings are not iterable."""
    out = ""
    for i in range(len(s)):
        ch = s[i]
        if ch.isdigit():
            out += ch
        elif out:
            break
    return out

def wait_color(when):
    """Red when you need to run, green when you have time."""
    if when.lower() in ("now", "due", "arriving"):
        return COLOR_SOON
    digits = _leading_digits(when)
    if digits and int(digits) <= 3:
        return COLOR_SOON
    return COLOR_OK

# tom-thumb glyphs are 3px wide with 1px of spacing.
CHAR_W = 4
WAIT_W = 13  # fits "now" and up to two digits plus the "m"

def fit_text(text, width):
    """Cut text to what actually fits, then left-align it in that width.

    A Box centres its child, so text wider than the box overflows at both ends
    and you read its middle -- "Midtown / W. 39th St." shows up as
    "wn / W. 39th". Trimming first, then padding the remainder, keeps every row
    starting at the same column.
    """
    room = width // CHAR_W
    shown = text[:room] if len(text) > room else text
    pad = width - CHAR_W * len(shown)
    children = [render.Text(content = shown, font = FONT, color = COLOR_TEXT)]
    if pad > 0:
        children.append(render.Box(width = pad, height = 7))
    return render.Row(children = children)

def watch_line(item):
    """One watched stop as a single row: route badge, where it goes, minutes.

    The stop itself is deliberately not shown. Four rows of "Blvd East at 47th
    St" would fill the screen with names already known -- what changes, and
    what is worth a glance, is where the next one goes and how long it is away.
    """
    stop = item["stop"]
    dep = item["dep"]

    if not dep:
        return render.Row(
            cross_align = "center",
            children = [
                render.Box(width = 3, height = 7, color = badge_color(stop, "")),
                render.Box(width = 2, height = 7),
                fit_text(item["err"] or "no service", 59),
            ],
        )

    route = dep["route"]
    badge_w = min(CHAR_W * len(route) + 3, 26) if route else 3
    dest_w = 64 - badge_w - 1 - WAIT_W

    color = badge_color(stop, route)
    if route:
        badge = render.Box(
            width = badge_w,
            height = 7,
            color = color,
            child = render.Text(
                content = route,
                font = FONT,
                color = text_on(color),
            ),
        )
    else:
        # Ferries have no useful route name -- the route is its destination --
        # so the badge shrinks to a plain colour stripe.
        badge = render.Box(width = badge_w, height = 7, color = color)

    return render.Row(
        cross_align = "center",
        children = [
            badge,
            render.Box(width = 1, height = 7),
            fit_text(dep["dest"], dest_w),
            render.Box(
                width = WAIT_W,
                height = 7,
                child = render.Text(
                    content = _short_wait(dep["when"]),
                    font = FONT,
                    color = wait_color(dep["when"]),
                ),
            ),
        ],
    )

def _short_wait(when):
    """'12 min' -> '12'. The column is too narrow to spell it out."""
    w = when.strip()
    if w.lower() in ("now", "due", "arriving"):
        return "now"
    digits = _leading_digits(w)
    if digits:
        return digits + "m"
    return w[:5]

def page_of(items):
    """One screen: up to four watched stops, padded to a stable height."""
    rows = []
    for item in items:
        rows.append(watch_line(item))
        rows.append(render.Box(height = 1))
    return render.Column(children = rows)

def message_screen(text):
    return render.Root(
        child = render.Box(
            child = render.WrappedText(
                content = text,
                font = FONT,
                color = COLOR_DIM,
                align = "center",
            ),
        ),
    )

def unwrap_stop(raw):
    """Decode a stop value, tolerating pixlet's selection envelope.

    A LocationBased selection does not arrive as the string put in
    schema.Option.value; pixlet wraps it as {"display": ..., "value": ...}, so
    the real payload is one decode deeper.
    """
    if not raw or raw == SLOT_UNUSED:
        return json.decode(DEFAULT_STOP)

    stop = json.decode(raw)
    if type(stop) == "dict" and "m" not in stop and "value" in stop:
        stop = json.decode(stop["value"])

    # Anything unrecognisable falls back rather than crashing the render.
    if type(stop) != "dict" or "m" not in stop or "c" not in stop:
        return json.decode(DEFAULT_STOP)
    return stop

def stop_configured(raw):
    """Has this slot actually been given a stop?"""
    if not raw or raw == SLOT_UNUSED:
        return False
    decoded = json.decode(raw)
    if type(decoded) == "dict" and "value" in decoded and "m" not in decoded:
        decoded = json.decode(decoded["value"])
    return type(decoded) == "dict" and "c" in decoded and "m" in decoded

def configured_slots(config):
    """The slots that have been filled in, in the order they appear."""
    out = []
    for slot in range(1, SLOTS + 1):
        raw = config.get("stop%d" % slot)
        if not stop_configured(raw):
            continue
        out.append({"stop": unwrap_stop(raw)})
    return out

def next_departures(slot, now, count):
    """The soonest departures for one watched stop, after its direction filter.

    Asks for `count` because the screen holds four rows however many stops are
    being watched: one stop fills them with its own next four, two stops take
    two each. Leaving the bottom half black wastes the only space there is.
    """
    stop = slot["stop"]
    if stop["m"] == "l":
        departures, err = scheduled_departures("lr", stop["c"], now)
    elif stop["m"] == "f":
        departures, err = scheduled_departures("fr", stop["c"], now)
    else:
        departures, err = bus_departures(stop["c"])

    if err:
        return [{"stop": stop, "dep": None, "err": err}]

    filtered = filter_by_direction(departures, stop.get("d", []))
    if type(filtered) == "string":
        return [{"stop": stop, "dep": None, "err": "none that way"}]
    if not filtered:
        return [{"stop": stop, "dep": None, "err": "no departures"}]

    out = []
    for dep in filtered[:count]:
        out.append({"stop": stop, "dep": dep, "err": None})
    return out

def main(config):
    tz = config.get("$tz", "America/New_York")
    now = time.now().in_location(tz)

    slots = configured_slots(config)
    if not slots:
        return message_screen("pick a stop")

    items = []
    if len(slots) >= LINES_PER_PAGE:
        # Every row is spoken for; one departure each, and page through them.
        for slot in slots:
            items.extend(next_departures(slot, now, 1))
    else:
        # Fewer stops than rows, so hand out the spare rows rather than
        # leaving the bottom of the screen black. Earlier slots get the
        # remainder, since they were chosen first.
        each = LINES_PER_PAGE // len(slots)
        spare = LINES_PER_PAGE % len(slots)
        for i, slot in enumerate(slots):
            want = each + (1 if i < spare else 0)
            got = next_departures(slot, now, want)

            # A stop with nothing to show still only needs its one line; give
            # what it did not use back to the others.
            items.extend(got)

    pages = []
    for start in range(0, len(items), LINES_PER_PAGE):
        pages.append(page_of(items[start:start + LINES_PER_PAGE]))

    if len(pages) == 1:
        return render.Root(delay = DELAY_MS, max_age = MAX_AGE, child = pages[0])

    # render.Animation gives each child exactly one frame, so a page has to be
    # repeated to stay up long enough to read.
    frames = []
    repeats = PAGE_HOLD_MS // DELAY_MS
    for page in pages:
        for _ in range(repeats):
            frames.append(page)

    return render.Root(
        delay = DELAY_MS,
        max_age = MAX_AGE,
        show_full_animation = True,
        child = render.Animation(children = frames),
    )

def stop_options(location, mode = ""):
    """Nearby stops, one option per direction of travel.

    Direction is baked into the option rather than offered as a second field.
    A schema.Generated can only source from a *statically declared* field, and
    these dropdowns are themselves generated -- pixlet rejects the schema with
    "references source that does not exist: stop1". So each option has to be
    self-contained: which stop to query, and which way it is going.

    This runs on Tidbyt's servers when someone configures the app, not on the
    device, so it can afford to download a grid cell and sort it.
    """
    loc = json.decode(location)
    lat = float(loc["lat"])
    lon = float(loc["lng"])

    options = []
    for (dist_km, stop) in nearby_stops(lat, lon, mode):
        stop_mode = stop.get("m", "b")

        # Starlark's % operator has no precision specifier, so round by hand.
        tenths = int(dist_km * 0.621371 * 10 + 0.5)
        miles = "%d.%d" % (tenths // 10, tenths % 10)

        routes = ", ".join(stop.get("r", [])[:4])
        suffix = " - %s" % routes if routes and stop_mode != "f" else ""

        for entry in stop_directions(stop):
            label = MODE_TAGS.get(stop_mode, "BUS") + MODE_SEPARATOR + stop["n"]
            if entry["l"]:
                label += " to %s" % entry["l"]

            options.append(
                schema.Option(
                    display = "%s%s (%s mi)" % (label, suffix, miles),
                    value = json.encode({
                        "c": stop["c"],
                        "m": stop_mode,
                        "d": entry["m"],
                    }),
                ),
            )

    if not options:
        options.append(
            schema.Option(
                display = "Nothing found nearby",
                value = SLOT_UNUSED,
            ),
        )
    return options

def stop_directions(stop):
    """Every way a rider can leave this stop, as {l: label, m: terminals}.

    Falls back to a single unlabelled entry when a stop has no direction data,
    so it still appears rather than vanishing.
    """
    entries = fetch_destinations(stop)
    if not entries:
        return [{"l": stop.get("t", ""), "m": []}]
    return entries

def stop_fields(location):
    """Every slot's dropdown, built from the one address.

    All six come from a single generated field on purpose. Pixlet's config UI
    keys a generated field by its `source`, so six of them sourced from the
    same address collapse into one -- whichever reply arrives last is the only
    slot that appears. A handler may return several fields, which sidesteps
    that entirely and computes the nearby list once instead of six times.
    """
    options = [schema.Option(display = "Not used", value = SLOT_UNUSED)]
    options.extend(stop_options(location))

    fields = []
    for slot in range(1, SLOTS + 1):
        fields.append(
            schema.Dropdown(
                id = "stop%d" % slot,
                name = "Stop %d" % slot,
                desc = "Nearest first. Leave as Not used to skip.",
                icon = "route",
                default = SLOT_UNUSED,
                options = options,
            ),
        )
    return fields

def get_schema():
    """One address, then six stop slots shown in the order they are filled in.

    The address is a single schema.Location. Each slot is a dropdown generated
    from it, so nearby stops are computed once per location rather than asking
    for the same address six times over.

    Pixlet builds its handler table from this static schema and keys it by
    field id, so a handler that only appears on a *generated* field is never
    registered -- requesting its options answers "no exported handler named
    ...". Generated fields may therefore return dropdowns, which carry no
    handler, but not a LocationBased, which does.
    """
    return schema.Schema(
        version = "1",
        fields = [
            schema.Location(
                id = "home",
                name = "Location",
                desc = "Your address. Everything below is measured from here.",
                icon = "locationDot",
            ),
            schema.Generated(
                id = "stop_pickers",
                source = "home",
                handler = stop_fields,
            ),
        ],
    )
