#!/usr/bin/env python3
"""
Produce a development copy of the app wired to the local mock server.

The shipped app talks to raw.githubusercontent.com and the real NJ Transit API,
and reads credentials through secret.decrypt(), which deliberately returns None
outside Tidbyt's cloud. None of that is reachable while developing, so this
rewrites those three seams to point at pipeline/mock_server.py.

    python3 pipeline/mock_server.py &
    python3 pipeline/make_dev_copy.py
    pixlet serve .dev/nj_transit_dev.star

The copy lands in .dev/ (gitignored) so the real app file is never edited with
development-only values that could be committed by accident.
"""

import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "nj_transit_nearby.star"
OUT_DIR = ROOT / ".dev"
OUT = OUT_DIR / "nj_transit_dev.star"

MOCK = "http://127.0.0.1:8777"

# pixlet render/serve gets confused when several .star files share a directory,
# so the dev copy gets one to itself.
REPLACEMENTS = [
    (
        'DATA_BASE = "https://raw.githubusercontent.com/joshbrewster42/tidbyt-nj-transit/main/data/v1"',
        'DATA_BASE = "%s"' % MOCK,
    ),
    (
        'BUS_API = "https://pcsdata.njtransit.com/api/BUSDV2"',
        'BUS_API = "%s/api/BUSDV2"' % MOCK,
    ),
    (
        "    username = secret.decrypt(NJT_USERNAME_ENC)\n"
        "    password = secret.decrypt(NJT_PASSWORD_ENC)",
        "    # DEV COPY: secret.decrypt() returns None locally, so the mock\n"
        "    # server accepts these placeholders instead.\n"
        '    username = "dev"\n'
        '    password = "dev"',
    ),
]


def main():
    if not SRC.exists():
        sys.exit("Missing %s" % SRC)

    src = SRC.read_text()
    for old, new in REPLACEMENTS:
        if old not in src:
            sys.exit(
                "Could not find this text to patch -- the app changed shape:\n\n%s" % old)
        src = src.replace(old, new, 1)

    OUT_DIR.mkdir(exist_ok=True)
    OUT.write_text(
        "# GENERATED by pipeline/make_dev_copy.py -- do not edit, do not commit.\n"
        "# Points at the local mock server instead of the real API.\n" + src)
    print("Wrote %s" % OUT.relative_to(ROOT))
    print("Now: pixlet serve %s" % OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
