#!/usr/bin/env python3
"""
Produce a development copy of the app wired to the local mock server.

The shipped app talks to raw.githubusercontent.com and the real NJ Transit API,
and reads credentials through secret.decrypt(), which deliberately returns None
outside Tidbyt's cloud. None of that is reachable while developing, so this
rewrites those three seams to point at pipeline/mock_server.py.

    python3 pipeline/mock_server.py &
    python3 pipeline/make_dev_copy.py
    pixlet serve .dev/nj_departures_dev.star

The copy lands in .dev/ (gitignored) so the real app file is never edited with
development-only values that could be committed by accident.
"""

import argparse
import getpass
import os
import pathlib
import stat
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "nj_departures.star"
OUT_DIR = ROOT / ".dev"
OUT = OUT_DIR / "nj_departures_dev.star"
# Its own directory: pixlet mis-resolves paths when several .star files share
# one, reporting "reading <other file>: file does not exist".
LIVE_DIR = OUT_DIR / "live"
LIVE_OUT = LIVE_DIR / "nj_departures_live.star"

MOCK = "http://127.0.0.1:8777"

# pixlet render/serve gets confused when several .star files share a directory,
# so the dev copy gets one to itself.
REPLACEMENTS = [
    (
        'DATA_BASE = "https://raw.githubusercontent.com/joshbrewster42/tidbyt-nj-transit/main/data/v1"',
        'DATA_BASE = "%s"' % MOCK,
    ),
    (
        'BUS_API = "https://pcsdata.njtransit.com/api/BUSDV2"',
        'BUS_API = "%s/api/BUSDV2"' % MOCK,
    ),
    (
        "    username = secret.decrypt(NJT_USERNAME_ENC)\n"
        "    password = secret.decrypt(NJT_PASSWORD_ENC)",
        "    # DEV COPY: secret.decrypt() returns None locally, so the mock\n"
        "    # server accepts these placeholders instead.\n"
        '    username = "dev"\n'
        '    password = "dev"',
    ),
]


def make_live():
    """A copy that talks to the real API with real credentials.

    secret.decrypt() only works inside Tidbyt's cloud, so an encrypted
    credential cannot be exercised on this machine -- and `pixlet push` renders
    locally, which means even a push to a device shows "no api key". This is
    the only way to see live bus departures before the app is published.

    The credentials go into the file in plain text. It is written to .dev/,
    which is gitignored, and chmod 600. Delete it when finished.
    """
    username = os.environ.get("NJT_USERNAME")
    password = os.environ.get("NJT_PASSWORD")
    try:
        if not username:
            username = input("NJ Transit username: ").strip()
        if not password:
            password = getpass.getpass("NJ Transit password: ")
    except (EOFError, KeyboardInterrupt):
        sys.exit("\nNeeds a terminal, or set NJT_USERNAME and NJT_PASSWORD.")

    if not username or not password:
        sys.exit("Need both a username and a password.")

    src = SRC.read_text()
    old = ("    username = secret.decrypt(NJT_USERNAME_ENC)\n"
           "    password = secret.decrypt(NJT_PASSWORD_ENC)")
    if old not in src:
        sys.exit("Could not find the secret.decrypt calls to replace.")
    src = src.replace(old,
                      "    # LOCAL COPY -- real credentials in plain text.\n"
                      "    username = %r\n    password = %r" % (username, password))

    LIVE_DIR.mkdir(parents=True, exist_ok=True)
    LIVE_OUT.write_text(
        "# GENERATED by make_dev_copy.py --live -- CONTAINS REAL CREDENTIALS.\n"
        "# Gitignored and chmod 600. Delete it when you are done:\n"
        "#   rm %s\n" % LIVE_OUT.relative_to(ROOT) + src)
    LIVE_OUT.chmod(stat.S_IRUSR | stat.S_IWUSR)

    print("Wrote %s (mode 600, gitignored)" % LIVE_OUT.relative_to(ROOT))
    print()
    print("  Live browser preview:")
    print("    DEVUI_APP=%s python3 pipeline/devui.py" % LIVE_OUT.relative_to(ROOT))
    print()
    print("  This file holds your password in plain text. Remove it after:")
    print("    rm %s" % LIVE_OUT.relative_to(ROOT))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--live", action="store_true",
                    help="build a copy using the real API and real credentials")
    args = ap.parse_args()

    if not SRC.exists():
        sys.exit("Missing %s" % SRC)

    if args.live:
        return make_live()

    src = SRC.read_text()
    for old, new in REPLACEMENTS:
        if old not in src:
            sys.exit(
                "Could not find this text to patch -- the app changed shape:\n\n%s" % old)
        src = src.replace(old, new, 1)

    OUT_DIR.mkdir(exist_ok=True)
    OUT.write_text(
        "# GENERATED by pipeline/make_dev_copy.py -- do not edit, do not commit.\n"
        "# Points at the local mock server instead of the real API.\n" + src)
    print("Wrote %s" % OUT.relative_to(ROOT))
    print("Now: pixlet serve %s" % OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
